name: accessibility
on:
  push:
    branches:
      - main
jobs:
  check-accessibility:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: a11ywatch/github-action@v1.14.0
        with:
          WEBSITE_URL: $localhost:3000
          SUBDOMAINS: true
          TLD: false
          SITEMAP: true
          FAIL_ERRORS_COUNT: 1
          LIST: true
          FIX: false
          UPGRADE: false
          COMPUTER_VISION_SUBSCRIPTION_KEY: ${{ secrets.COMPUTER_VISION_SUBSCRIPTION_KEY }}
          COMPUTER_VISION_ENDPOINT: ${{ secrets.COMPUTER_VISION_SUBSCRIPTION_KEY }}
