name: Accessibility Checker

on: [push, pull_request]

jobs:
  accessibility-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Accessibility Tests
        uses: dacastdotcom/a11y-action@v3.3
        with:
          path: 'public'
          reporter: 'v3'
          levels: 'A, AA'
