name: accessability
run-name: Axe-core accessibility test
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install @axe-core/cli -g
      - run: npx http-server
      - run: npm start & npx wait-on http://localhost:3000
      - name: Run Axe-core accessibility test
        run: axe http://localhost:3000
