name: accessability
run-name: Axe-core accessibility test
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install http-server and wait-onn
        run: npm start & npx wait-on http://localhost:3000
      - name: Run Axe-core accessibility test
        run: npx axe http://localhost:8080
