name: accessibility
on:
  push:
    branches:
      - main
jobs:
  check-accessibility:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install http-server and wait-on
        run: npm install http-server wait-on -g
      - name: Start http-server and wait for it to be ready
        run: |
          http-server -p 8080 &
          wait-on http://127.0.0.1:8080
      - name: Run Axe-core accessibility test
        run: npx axe http://localhost:8080
